language: go

go:
    - 1.8
    - 1.9
    - tip

script:
    - go test -coverprofile=coverage.txt -covermode=atomic

after_success:
    - bash <(curl -s https://codecov.io/bash)

addons:
    code_climate:
        repo_token: dbdf4ee7f398b306062f9fbd160fc5efc161b2a5744cd4f4a44e6aaded7ca0d8
